theme = "hugo-theme-novela"
baseURL = "https://hamdiahmed.com"
languageCode = "en-us"
title = "Bits & Thoughts"

[social]


[taxonomies]
author = "Hamdi Ahmed"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
      

      

