theme = "hugo-theme-novela"
baseURL = ""
languageCode = "en-us"
title = "test"

# Novela settings

paginate = 6

[social]
twitter= "https://twitter.com/forestryio"
github= "https://github.com/forestryio/novela-hugo-starter"
linkedin= "https://www.linkedin.com/company/forestry.io"
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"

[markup.goldmark.renderer]
unsafe= true

[params]
Title = "Test"

