theme = "hugo-theme-novela"
baseURL = ""
languageCode = "en-us"
title = "Bits & Thoughts"



# Novela settings

paginate = 6

[social]
twitter= "https://https://twitter.com/hhamdiahmed"

[taxonomies]
author = "Hamdi Ahmed"

[markup.goldmark.renderer]
unsafe= true





