theme = "hugo-theme-novela"
baseURL = ""
languageCode = "en-us"
title = "My New Hugo Site"

# Novela settings

paginate = 6

[social]
twitter= "https://twitter.com/forestryio"
github= "https://github.com/forestryio/novela-hugo-starter"
linkedin= "https://www.linkedin.com/company/forestry.io"
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"

[markup.goldmark.renderer]
unsafe= true

############################
## Code folding
############################

# Set to true to disable code folding
disable_codefolding = false
# Set to "hide" or "show" all codes by default
codefolding_show = "show"
# Set to true to exclude the "Show/hide all" button
codefolding_nobutton = false
    
